# Generated by Django 5.2.1 on 2025-10-17 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('Forensic Service', 'Forensic Service'), ('Audit', 'Audit'), ('Tax', 'Tax'), ('Consulting', 'Consulting'), ('Advisory', 'Advisory'), ('Technology', 'Technology'), ('Managed Service', 'Managed Service')], max_length=50)),
                ('site_address', models.TextField()),
                ('date_of_job', models.DateField()),
                ('summary_of_work', models.TextField()),
                ('client_name', models.CharField(max_length=255)),
                ('poc_name', models.CharField(max_length=255)),
                ('poc_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_field_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldJobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_approval_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_code_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fieldwork.fieldjob')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('field_job', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('site_visit_complete', models.BooleanField(default=False)),
                ('revisit_required', models.BooleanField(default=False)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('summary_of_work_performed', models.TextField(blank=True)),
                ('fe_signature', models.CharField(blank=True, max_length=255)),
                ('submission_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('submission_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('submission_location_address', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_report', to='fieldwork.fieldjobassignment')),
            ],
        ),
    ]
