# Generated by Django 5.2.1 on 2025-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldjob',
            name='date_of_job',
            field=models.DateTimeField(),
        ),
    ]
