# Generated by Django 3.2.25 on 2025-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_Name',
            field=models.CharField(default='Unnamed Office', max_length=255),
        ),
    ]
