# Generated by Django 3.2.25 on 2025-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
