# Generated by Django 3.2.25 on 2025-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taskfile_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfile',
            name='file',
        ),
        migrations.AddField(
            model_name='taskfile',
            name='cloudinary_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
