# Generated by Django 5.2.1 on 2025-10-03 05:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250921_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=core.models.get_timezone_choices, default='UTC', help_text="The IANA timezone for this user (e.g., 'America/New_York').", max_length=50),
        ),
    ]
