# Generated by Django 5.2.1 on 2025-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='google_map_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
