# Generated by Django 5.2.1 on 2025-12-16 10:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_office_google_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('second_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office_focus', models.TextField(blank=True, help_text='Main focus areas of the office', null=True)),
                ('community_involvement', models.TextField(blank=True, help_text='Community involvement and initiatives', null=True)),
                ('principal_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('principal_business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('principal_photo', cloudinary.models.CloudinaryField(blank=True, help_text='Photo of the principal in charge', max_length=255, null=True, verbose_name='principal_photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.OneToOneField(help_text='The office this information belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.office')),
            ],
            options={
                'verbose_name': 'Office Detail',
                'verbose_name_plural': 'Office Details',
            },
        ),
    ]
