# Generated by Django 5.2.1 on 2025-12-21 05:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_officedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('north_america', 'North America'), ('south_america', 'South America'), ('europe', 'Europe'), ('asia', 'Asia'), ('africa', 'Africa'), ('middle_east', 'Middle East'), ('oceania', 'Oceania')], default='africa', max_length=50)),
                ('region_title', models.CharField(default='Head of Africa Region', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, help_text='Profile photo of the regional leader', max_length=255, null=True, verbose_name='profile_image')),
                ('bio', models.TextField(blank=True, help_text='Professional biography', null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('joining_date', models.CharField(blank=True, help_text='e.g., March 2018', max_length=100, null=True)),
                ('regional_expertise', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('company_impact', models.TextField(blank=True, null=True)),
                ('leadership_style', models.TextField(blank=True, null=True)),
                ('market_insights', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which leaders are displayed (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regional Leader',
                'verbose_name_plural': 'Regional Leaders',
                'ordering': ['display_order', 'region', 'last_name'],
            },
        ),
    ]
