# Generated by Django 5.2.1 on 2025-12-21 13:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_regionalleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position_title', models.CharField(default='Managing Partner', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, help_text='Profile photo of the managing partner', max_length=255, null=True, verbose_name='profile_image')),
                ('bio', models.TextField(help_text='Professional biography')),
                ('education', models.TextField()),
                ('joining_date', models.DateField(help_text='Date when they became Managing Partner')),
                ('expertise', models.TextField(help_text='Areas of expertise and specializations')),
                ('achievements', models.TextField(help_text='Notable achievements and accomplishments')),
                ('company_impact', models.TextField(help_text='Impact on the company')),
                ('leadership_philosophy', models.TextField(help_text='Leadership philosophy and style')),
                ('strategic_vision', models.TextField(help_text='Strategic vision for the company')),
                ('years_in_role', models.IntegerField(default=0, help_text='Years served as Managing Partner')),
                ('previous_positions', models.TextField(blank=True, help_text='Previous positions held', null=True)),
                ('board_memberships', models.TextField(blank=True, help_text='Current board memberships', null=True)),
                ('awards', models.TextField(blank=True, help_text='Awards and recognitions', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which partners are displayed (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Managing Partner',
                'verbose_name_plural': 'Managing Partners',
                'ordering': ['display_order', 'last_name'],
            },
        ),
    ]
