# Generated by Django 5.2.1 on 2025-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_managingpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalleader',
            name='region',
            field=models.CharField(choices=[('all', 'All Regions'), ('north_america', 'North America'), ('south_america', 'South America'), ('europe', 'Europe'), ('asia', 'Asia'), ('africa', 'Africa'), ('middle_east', 'Middle East'), ('oceania', 'Oceania')], default='africa', max_length=50),
        ),
    ]
