"""
Django settings for ey_website project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# settings.py (at the very top)
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6qie*%tx8#%7sr7kch=mt+y=^fyd8ajekc04n@_mntmws5m-p5'



# Allow all hosts - USE WITH CAUTION IN PRODUCTION!
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'cloudinary',
    'cloudinary_storage',
    'newsletter',  # <-- Add the new app here
    'widget_tweaks',  # Add this line
    'chatbot',

]

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME = 'dpupwwixw'
CLOUDINARY_API_KEY = '455943441687337'
CLOUDINARY_API_SECRET = '45L4allKMFrnzOaGYOYt6NXYAFk'

# Cloudinary storage settings
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': CLOUDINARY_API_KEY,
    'API_SECRET': CLOUDINARY_API_SECRET,
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ey_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ey_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test',
        'USER': 'JmKhKqoAam5FV5E.root',
        'PASSWORD': '3130TGcNFxkHKrDj',
        'HOST': 'gateway01.eu-central-1.prod.aws.tidbcloud.com',
        'PORT': 4000,
        # ADD THIS LINE for persistent connections to prevent connection loss (Error 2013)
        'CONN_MAX_AGE': 48000, # Keep connections open for up to 10 minutes (600 seconds)
        'OPTIONS': {
            'ssl': {
                'ca': os.path.join(BASE_DIR, 'cert', 'isrgrootx1.pem')
            }
        }
    }
}

# Fallback to SQLite if MySQL connection fails (for development)
try:
    import mysql.connector
    conn = mysql.connector.connect(
        host='gateway01.eu-central-1.prod.aws.tidbcloud.com',
        user='JmKhKqoAam5FV5E.root',
        password='3130TGcNFxkHKrDj',
        port=4000,
        database='test'
    )
    conn.close()
except Exception as e:
    print(f"MySQL connection failed: {e}. Falling back to SQLite.")
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'core/static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'core.User'

# Security settings - adjust these based on your environment
DEBUG = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}
# settings.py

# ... other settings
# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465       # MODIFIED: Changed from 587
EMAIL_USE_TLS = False  # MODIFIED: Changed from True
EMAIL_USE_SSL = True   # ADDED: Must be True for port 465

# MODIFIED: Fetch sensitive credentials from environment variables (Render/production setting)
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')

GEMINI_API_KEY = 'AIzaSyBlxToNTAEUXmZtqgCV9XsZww6gu9QqB7Y'

# SET THESE TO PREVENT TIMEOUTS/CONNECTION RESETS ON LARGE FILE UPLOADS
# Django's default limit for request body size is often too small (2.5MB).
# Setting limits to 50MB should prevent errors during image uploads.

# Maximum size of a request body that Django will process (50 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 * 1024 * 1024

# Maximum size of an uploaded file that will be handled entirely in memory (50 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 * 1024 * 1024