# Generated by Django 5.2.1 on 2025-10-15 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('proposal_deadline', models.DateTimeField()),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client/user who submitted the proposal.', on_delete=django.db.models.deletion.CASCADE, related_name='rfp_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFPFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', models.URLField(help_text='Public URL of the file stored in Cloudinary.', max_length=500)),
                ('public_id', models.CharField(help_text='The Cloudinary public ID for deletion and management.', max_length=255)),
                ('file_type', models.CharField(choices=[('docx', 'DOCX'), ('html', 'HTML')], default='docx', help_text='File format type', max_length=10)),
                ('is_being_edited', models.BooleanField(default=False)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_rfp_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_rfp_files', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='rfp.rfpreferral')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalDocxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfp_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_docx', to='rfp.rfpfile')),
            ],
            options={
                'indexes': [models.Index(fields=['rfp_file', 'created_at'], name='rfp_origina_rfp_fil_3f86b6_idx')],
            },
        ),
    ]
