# Generated by Django 3.2.25 on 2025-09-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('audit', models.BooleanField(default=False)),
                ('tax', models.BooleanField(default=False)),
                ('consulting', models.BooleanField(default=False)),
                ('forensic_service', models.BooleanField(default=False)),
                ('managed_service', models.BooleanField(default=False)),
                ('technology_solution', models.BooleanField(default=False)),
                ('advisory', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('audit', models.BooleanField(default=False)),
                ('tax', models.BooleanField(default=False)),
                ('consulting', models.BooleanField(default=False)),
                ('forensic_service', models.BooleanField(default=False)),
                ('managed_service', models.BooleanField(default=False)),
                ('technology_solution', models.BooleanField(default=False)),
                ('advisory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
